package httpserver

import "net/http"

const (
	// URIPrefix ...
	URIPrefix = "/api/v1"

	// URIPrefixbank ...
	URIPrefixBank = URIPrefix + "/bank"

	// URIPathClientGetBalance ...
	URIPathClientGetBalance = URIPrefixBank + "/balance"
	// URIPathClientCreateAcc ...
	URIPathClientCreateAccount = URIPrefixBank + "/account"
	// URIPathClientAddToBell ...
	URIPathClientAddToBell = URIPrefixBank + "/add"

	// HTTPMethodCreatebank ...
	HTTPMethodGetBalance = http.MethodPost
	// HTTPMethodCreatebank ...
	HTTPMethodCreateAccount = http.MethodPost
	// HTTPMethodAddToBell ...
	HTTPMethodAddToBell = http.MethodPost
)
